name: Sync to deploy repo

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
          persist-credentials: false

      - name: Push to deploy repo
        run: |
          git push https://wnsjun:${{ secrets.DEPLOY_REPO_TOKEN }}@github.com/wnsjun/FE_ADMIN_DEPLOY.git HEAD:develop --force
